### ISSUE TITLE
Add the parent prefix to the ip-address query response via the api

### ISSUE THREAD

**Issue by phurrelmann** [digitalocean/netbox#3099]
### Environment
* Python version:  3.7.3 (dev), 3.5.3 (test)
* NetBox version:  2.6-dev (dev), 2.5.10 (test)

### Proposed Functionality

Currently when querying an ip-address via the API the response does not contain any reference to its parent prefix. The reference to the parent prefix should be present in the API response like it is visible in the WebUI. At least the id and the prefix should be included. Further prefix details could be easily retrieved via the prefix id then.

WebUI:
![webui_ip-address](https://user-images.githubusercontent.com/10113716/56570945-3214ed00-65bc-11e9-868b-4ecd2bffa743.png)

Current API-Response:
```yaml
{
  "count": 1,
  "next": null,
  "previous": null,
  "results": [
    {
      "id": 5063,
      "family": {
        "value": 4,
        "label": "IPv4"
      },
      "address": "10.100.16.105/30",
      "vrf": null,
      "tenant": {
        "id": 2,
        "url": "http://127.0.0.1:8000/api/tenancy/tenants/2/",
        "name": "XXX",
        "slug": "xxx"
      },
      "status": {
        "value": 1,
        "label": "Active"
      },
      "role": null,
      "interface": null,
      "nat_inside": null,
      "nat_outside": null,
      "dns_name": "",
      "description": "xxx",
      "tags": [],
      "created": "2018-04-24",
      "last_updated": "2018-04-24T08:31:13.842911Z"
    }
  ]
}
```

Proposed API-Response:
```yaml
{
  "count": 1,
  "next": null,
  "previous": null,
  "results": [
    {
      "id": 5063,
      "family": {
        "value": 4,
        "label": "IPv4"
      },
      "address": "10.100.16.105/30",
      "vrf": null,
      "tenant": {
        "id": 2,
        "url": "http://127.0.0.1:8000/api/tenancy/tenants/2/",
        "name": "XXX",
        "slug": "xxx"
      },
      "status": {
        "value": 1,
        "label": "Active"
      },
      "parent_prefix": {
        "id": 611,
        "prefix": "10.100.16.104/30"
      },
      "role": null,
      "interface": null,
      "nat_inside": null,
      "nat_outside": null,
      "dns_name": "",
      "description": "xxx",
      "tags": [],
      "created": "2018-04-24",
      "last_updated": "2018-04-24T08:31:13.842911Z"
    }
  ]
}
```

### Use Case

Using the API there is currently no direct connection/relation between an IP-address and its parent prefix. This enhancement would simplify the usage of the API and brings the API and WebUI in sync.

Real word Use-Case:
We have quite a lot of prefixes that contain BGP-cluster addresses with a /32 prefix length.
Due to the different prefix length (prefix vs. IP-address) it requires additional API calls to get the correct prefix for an IP-address and some additional logic is needed.

### Database Changes

none, all information is already existing

### External Dependencies

none
